// swift-tools-version: 6.2
import PackageDescription

let package = Package(
	name: "LeetCode",
	products: [
		.executable(name: "1", targets: ["1"]),
		.executable(name: "28", targets: ["28"]),
		.executable(name: "69", targets: ["69"]),
		.executable(name: "70", targets: ["70"]),
		.executable(name: "83", targets: ["83"]),
		.executable(name: "100", targets: ["100"]),
		.executable(name: "101", targets: ["101"]),
		.executable(name: "102", targets: ["102"]),
		.executable(name: "326", targets: ["326"]),
		.executable(name: "509", targets: ["509"]),
		.executable(name: "929", targets: ["929"]),
		.executable(name: "1323", targets: ["1323"]),
		.executable(name: "1324", targets: ["1324"]),
	],
	targets: [
		.executableTarget(name: "1"),
		.executableTarget(name: "28"),
		.executableTarget(name: "69"),
		.executableTarget(name: "70"),
		.executableTarget(name: "83"),
		.executableTarget(name: "100"),
		.executableTarget(name: "101"),
		.executableTarget(name: "102"),
		.executableTarget(name: "326"),
		.executableTarget(name: "509"),
		.executableTarget(name: "929"),
		.executableTarget(name: "1323"),
		.executableTarget(name: "1324"),
		.testTarget(name: "T1", dependencies: ["1"]),
		.testTarget(name: "T28", dependencies: ["28"]),
		.testTarget(name: "T69", dependencies: ["69"]),
		.testTarget(name: "T70", dependencies: ["70"]),
		.testTarget(name: "T83", dependencies: ["83"]),
		.testTarget(name: "T100", dependencies: ["100"]),
		.testTarget(name: "T101", dependencies: ["101"]),
		.testTarget(name: "T102", dependencies: ["102"]),
		.testTarget(name: "T326", dependencies: ["326"]),
		.testTarget(name: "T509", dependencies: ["509"]),
		.testTarget(name: "T929", dependencies: ["929"]),
		.testTarget(name: "T1323", dependencies: ["1323"]),
		.testTarget(name: "T1324", dependencies: ["1324"]),
	]
)
