// swift-tools-version: 6.2
import PackageDescription

let package = Package(
	name: "LeetCode",
	products: [
		.executable(name: "E1", targets: ["E1"]),
		.executable(name: "E20", targets: ["E20"]),
		.executable(name: "E28", targets: ["E28"]),
		.executable(name: "E53", targets: ["E53"]),
		.executable(name: "E69", targets: ["E69"]),
		.executable(name: "E70", targets: ["E70"]),
		.executable(name: "E83", targets: ["E83"]),
		.executable(name: "E100", targets: ["E100"]),
		.executable(name: "E101", targets: ["E101"]),
		.executable(name: "E102", targets: ["E102"]),
		.executable(name: "E118", targets: ["E118"]),
		.executable(name: "E121", targets: ["E121"]),
		.executable(name: "E203", targets: ["E203"]),
		.executable(name: "E231", targets: ["E231"]),
		.executable(name: "E326", targets: ["E326"]),
		.executable(name: "E509", targets: ["E509"]),
		.executable(name: "E929", targets: ["E929"]),
		.executable(name: "E1323", targets: ["E1323"]),
		.executable(name: "E1324", targets: ["E1324"]),
	],
	targets: [
		.executableTarget(name: "E1"),
		.executableTarget(name: "E20"),
		.executableTarget(name: "E28"),
		.executableTarget(name: "E53"),
		.executableTarget(name: "E69"),
		.executableTarget(name: "E70"),
		.executableTarget(name: "E83"),
		.executableTarget(name: "E100"),
		.executableTarget(name: "E101"),
		.executableTarget(name: "E102"),
		.executableTarget(name: "E118"),
		.executableTarget(name: "E121"),
		.executableTarget(name: "E203"),
		.executableTarget(name: "E231"),
		.executableTarget(name: "E326"),
		.executableTarget(name: "E509"),
		.executableTarget(name: "E929"),
		.executableTarget(name: "E1323"),
		.executableTarget(name: "E1324"),
		.testTarget(name: "T1", dependencies: ["E1"]),
		.testTarget(name: "T20", dependencies: ["E20"]),
		.testTarget(name: "T28", dependencies: ["E28"]),
		.testTarget(name: "T53", dependencies: ["E53"]),
		.testTarget(name: "T69", dependencies: ["E69"]),
		.testTarget(name: "T70", dependencies: ["E70"]),
		.testTarget(name: "T83", dependencies: ["E83"]),
		.testTarget(name: "T100", dependencies: ["E100"]),
		.testTarget(name: "T101", dependencies: ["E101"]),
		.testTarget(name: "T102", dependencies: ["E102"]),
		.testTarget(name: "T118", dependencies: ["E118"]),
		.testTarget(name: "T121", dependencies: ["E121"]),
		.testTarget(name: "T203", dependencies: ["E203"]),
		.testTarget(name: "T231", dependencies: ["E231"]),
		.testTarget(name: "T326", dependencies: ["E326"]),
		.testTarget(name: "T509", dependencies: ["E509"]),
		.testTarget(name: "T929", dependencies: ["E929"]),
		.testTarget(name: "T1323", dependencies: ["E1323"]),
		.testTarget(name: "T1324", dependencies: ["E1324"]),
	]
)
